# Generated by Django 5.1.5 on 2025-03-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='motor_control_id',
            field=models.IntegerField(choices=[(1, 'Motor 1'), (2, 'Motor 2'), (3, 'Motor 3')], default=1),
        ),
    ]
