# Generated by Django 5.1.5 on 2025-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_motor_remove_product_motor_control_id_product_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='motor_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
