# Generated by Django 5.1.5 on 2025-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_motor_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='motor_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
